import os
from pathlib import Path

# Resolve paths relative to the project root (parent of Scripts/)
# This makes the project portable regardless of its location on disk.
ROOT_DIR = Path(__file__).resolve().parent.parent
INPUT_DIR = ROOT_DIR / "Input"
ARCHIVE_DIR = INPUT_DIR / "archive"
DAILY_DIR = INPUT_DIR / "daily"
STATIC_DIR = INPUT_DIR / "static"

APP_DIR = ROOT_DIR / "App"
SCRIPTS_DIR = ROOT_DIR / "Scripts"
EXPORTS_DIR = ROOT_DIR / "Exports"
LOGS_DIR = ROOT_DIR / "Logs"

# Cloud / CI override: MP_DB_PATH=/data/marketpulse.duckdb
_env_db = os.environ.get("MP_DB_PATH", "").strip()
if _env_db:
    DB_PATH = Path(_env_db)
    DATABASE_DIR = DB_PATH.parent
else:
    DATABASE_DIR = ROOT_DIR / "Database"
    DB_PATH = DATABASE_DIR / "marketpulse.duckdb"

STATUS_PATH = DATABASE_DIR / "status.json"



EQUITY_LIST_FILE = STATIC_DIR / "EQUITY_L .csv"
SECTOR_FILE = STATIC_DIR / "sector.csv"

REQUIRED_DAILY_PATTERNS = {
    "bhavcopy": "sec_bhavdata_full_*.csv",
    "market_cap": "mcap*.csv",
    "fifty_two_week": "CM_52_wk_High_low_*.csv",
    "price_band": "sec_list_*.csv",
    "pe": "PE_*.csv",
    "bulk": "bulk.csv",
    "block": "block.csv",
}

EMA_WINDOWS = [10, 20, 50, 63, 100, 150, 200]
RETURN_WINDOWS = {
    "return_5d_pct": 5,
    "return_1m_pct": 21,
    "return_3m_pct": 63,
    "return_6m_pct": 126,
    "return_9m_pct": 189,
    "return_12m_pct": 252,
}

FRIENDLY_COLUMNS = {
    "symbol": "Symbol",
    "trade_date": "Date",
    "series": "Series",
    "close_price": "Close",
    "volume": "Day Vol",
    "avg_volume_20d": "20D Avg Vol",
    "turnover_cr": "T/O Cr",
    "turnover_1w_cr": "T/O 1W Cr",
    "turnover_1m_cr": "T/O 1M Cr",
    "delivery_pct": "Delivery %",
    "market_cap_cr": "MCap Cr",
    "pe": "P/E",
    "band": "Band",
    "ema_10": "10 EMA",
    "ema_20": "20 EMA",
    "ema_50": "50 EMA",
    "ema_100": "100 EMA",
    "ema_200": "200 EMA",
    "away_10ema_pct": "10EMA %",
    "away_10wema_pct": "10WEMA %",
    "away_10mema_pct": "10MEMA %",
    "away_52w_high_pct": "52W %",
    "away_52w_low_pct": "52W Low %",
    "away_database_high_pct": "Loaded High %",
    "distance_to_high_pct": "High %",
    "return_5d_pct": "5D %",
    "return_1m_pct": "1M %",
    "return_3m_pct": "3M %",
    "return_6m_pct": "6M %",
    "return_9m_pct": "9M %",
    "return_12m_pct": "12M %",
    "rvol": "RVOL",
    "day_change_pct": "Day %",
    "vol_shock": "Vol Shock",
    "avg_day_pct": "Avg Day %",
    "focus_score": "Focus Score",
    "prep_score": "Prep Score",
    "near_score": "Near Score",
    "rank": "#",
    "risks": "Risks",
    "setup": "Setup",
    "qty": "Qty",
    "avg_buy_price": "Avg Buy",
    "sell_price": "Sell Px",
    "unrealized_pct": "U/R %",
    "realized_pct": "Rlz %",
    "cmp": "CMP",
    "buy_date": "Buy Date",
    "sell_date": "Sell Date",
    "notes": "Notes",
    "tags": "Tags",
    "symbol_count": "Names",
    "symbols": "Symbols",
    "change_type": "Change",
    "avg_focus": "Avg Focus",
    "avg_rs": "Avg RS",
    "industry_state": "Industry State",
    "sector_state": "Sector State",
    "advance_count_pct": "Adv %",
    "buy_value_cr": "Buy Cr",
    "sell_value_cr": "Sell Cr",
    "net_value_cr": "Net Cr",
    "client_name": "Institution",
    "new_addition": "New",
    "first_seen_date": "First Seen",
    "deal_rows": "Deal Rows",
    "active_days": "Active Days",
    "symbol_list": "Symbols",
    "latest_deal_date": "Latest Deal",
    "latest_deal_value_cr": "Latest Deal Cr",
    "deal_days": "Deal Days",
    "client_count": "Clients",
    "deal_vs_close_pct": "Deal Vs Close %",
    "deal_volume_pct": "Deal Vol %",
    "atr_pct": "ATR %",
    "rs_percentile": "RS %",
    "rs_1y_percentile": "RS 1Y %",
    "rs_3m_percentile": "RS 3M %",
    "rsi_14": "RSI D",
    "rsi_14_w": "RSI W",
    "rsi_14_m": "RSI M",
    "bullish_rsi_divergence": "Bull Div D",
    "bearish_rsi_divergence": "Bear Div D",
    "bullish_rsi_divergence_w": "Bull Div W",
    "bearish_rsi_divergence_w": "Bear Div W",
    "bullish_rsi_divergence_m": "Bull Div M",
    "bearish_rsi_divergence_m": "Bear Div M",
    "signal": "Signal",
    "why": "Why",
    "trigger_date": "Trigger Date",
    "trigger_close": "Trigger Close",
    "trigger_ema_10": "Trigger 10 EMA",
    "trigger_ema_200": "Trigger 200 EMA",
    "trigger_fast_ma": "Trigger Fast MA",
    "trigger_slow_ma": "Trigger Slow MA",
    "fast_ma": "Fast MA",
    "slow_ma": "Slow MA",
    "wema_10": "10 WEMA",
    "wema_200": "200 WEMA",
    "mema_10": "10 MEMA",
    "mema_200": "200 MEMA",
    "similarity_score": "Similarity",
    "current_setup": "Current Setup",
    "what_matched": "What Matched",
    "breakout_date": "Breakout Date",
    "breakout_close": "Breakout Close",
    "forward_return_pct": "Forward %",
    "vcp_score": "VCP Score",
    "trend_score": "Trend Score",
    "contraction_score": "Contraction Score",
    "volume_dryup_score": "Volume Dry-up Score",
    "pivot_proximity_score": "Pivot Proximity",
    "vcp_state": "VCP State",
    "is_vcp": "Is VCP",
    "near_high_tight": "Tight Near High",
    "low_volatility_near_high": "Low Vol Near High",
    "ema_stack_bullish": "EMA Stack Bull",
    "fresh_200ema_reclaim": "200EMA Reclaim",
    "ema_shakeout": "EMA Shakeout",
    "confirmed_morning_star_w": "MS W",
    "confirmed_morning_star_m": "MS M",
    "bullish_rsi_divergence_w": "Bull Div W",
    "bullish_rsi_divergence_m": "Bull Div M",
    "bearish_rsi_divergence_w": "Bear Div W",
    "bearish_rsi_divergence_m": "Bear Div M",
    "confirmed_hammer": "Hammer",
    "confirmed_bullish_engulfing": "Bull Engulf",
    "confirmed_shooting_star_w": "SS W",
    "confirmed_shooting_star_m": "SS M",
    "inside_bar": "Inside Bar",
    "nr7": "NR7",
    "price_up_delivery_up": "Price+Deliv Up",
    "delivery_spike": "Deliv Spike",
    "deal_value_cr": "Deal Cr",
    "deal_pct_volume": "Deal Vol %",
    "deal_price_vs_close_pct": "Deal Vs Close %",
    "repeated_client_count": "Repeat Client",
    "rotation_state": "State",
    "rotation_score": "Rotation Score",
    "score_change_5d": "5D Score",
    "rank_change_5d": "5D Rank",
    "rank_change_20d": "20D Rank",
    "turnover_expansion": "T/O Expansion",
    "broad_sector": "Broad Sector",
    "sector": "Sector",
    "broad_industry": "Broad Industry",
    "industry": "Industry",
    "clients": "Clients",
    "status": "Status",
    "prev_bucket": "Prev Bucket",
    "bucket": "Bucket",
    "has_deal": "Has Deal",
    "buy_deal_cr": "Buy Deal Cr",
    "sell_deal_cr": "Sell Deal Cr",
    "pnl_amount": "P/L INR",
    "pnl_pct": "P/L %",
    "r_multiple": "R",
    "entry_price": "Entry",
    "quantity": "Qty",
    "stop_loss": "Stop",
    "target": "Target",
    "trade_type": "Type",
    "setup_type": "Setup",
    "exit_price": "Exit",
    "exit_date": "Exit Date",
    "exit_reason": "Exit Reason",
    "mistake_tag": "Mistake",
    "risk_amount": "Risk Amt",
    "risk_pct": "Risk %",
    "current_close": "Current",
    "ema_200": "200 EMA",
    "entry_breadth_state": "Entry Breadth",
    "entry_sector_state": "Entry Sector State",
    "entry_sector_rs": "Entry Sector RS",
    "delivery_trend_5d": "Deliv Trend 5D",
    "return_1d_pct": "Return D",
    "rank_in_group": "Rank in Group",
    "turnover_1w_cr": "Turnover W (Cr)",
    "turnover_1m_cr": "Turnover M (Cr)",
}

SPECIAL_SCREENER_DEFAULTS = {
    "min_market_cap_cr": 1000,
    "min_volume": 1_000_000,
    "min_avg_volume_20d": 1_000_000,
    "min_52w_low_pct": 25,
    "lookback_days": 10,
}

WATCHLIST_BUCKETS = [
    ("0_2%", 0, 2),
    ("2_5%", 2, 5),
    ("5_10%", 5, 10),
    ("10%+", 10, None),
]
